### ISSUE TITLE
Thanks bro

### ISSUE THREAD

**Issue by chugo-admin** [germanynick/n8n-nodes-binance#1]
Hello bro, 

Thanks for this binance node n8n version.  
I tried to modify and make it generic by modifying the code to be like this so it can be able to do Market trade, Take Profit and Stop Loss for futures trade.

![image](https://github.com/germanynick/n8n-nodes-binance/assets/99708363/3f1fc54a-0e05-464e-bf93-11241683bd00)

![image](https://github.com/germanynick/n8n-nodes-binance/assets/99708363/c41f2a7d-d24a-4ca2-aa69-9552908e7d55)

<img width="598" alt="image" src="https://github.com/germanynick/n8n-nodes-binance/assets/99708363/10f43c83-32c5-4287-a503-28b5cca6c671">

<img width="706" alt="image" src="https://github.com/germanynick/n8n-nodes-binance/assets/99708363/85fdfd66-c585-4899-85f3-bc46c41f183c">

**Comment by germanynick** [comment]
Thank you, @chugo-admin 

For common scenarios, consider creating a new operation. Your code will be executed based on the operator type, and it's not too difficult to implement. Could you guide me through creating a pull request for it? Thanks for your contribution!
<img width="693" alt="Screenshot 2024-01-30 at 12 37 17 AM" src="https://github.com/germanynick/n8n-nodes-binance/assets/6898912/14daf0c3-6cd0-4fa3-9eb9-47aaa2298e4d">

**Comment by germanynick** [comment]
I just updated a new version that support custom function. (PR: #2)
You can try here [n8n-nodes-binance](https://www.npmjs.com/package/n8n-nodes-binance) v0.0.4
Demo:
<img width="948" alt="Screenshot 2024-03-21 at 11 07 52 PM" src="https://github.com/germanynick/n8n-nodes-binance/assets/6898912/a39540fd-7321-4f71-9b77-eb41f6897ae9">

List of function name + params will be defined in package [binance-api-node](https://www.npmjs.com/package/binance-api-node)
<img width="846" alt="Screenshot 2024-03-21 at 11 16 42 PM" src="https://github.com/germanynick/n8n-nodes-binance/assets/6898912/20f95d30-2640-489b-a2a3-eabb7ef22452">
